services:
  - type: web
    name: crccf-qrcode
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
